name: Check Clang Format

on:
    push:
      branches:
        - main
      tags:
        - '*'
    pull_request:
  
jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format-15
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main"
          sudo apt-get update
          sudo apt-get install -y clang-format-15

      - name: Check C/H files formatting (skip nRF)
        run: |
          find app drv mari \( -name "*.c" -o -name "*.h" \) \
            -exec clang-format-15 --dry-run --Werror {} +
